## Tujuan

Tahap ini bertujuan untuk memuat dataset ke dalam lingkungan Python serta memahami struktur dan karakteristik data. Proses ini mencakup identifikasi tipe data, jumlah data, serta pengecekan awal terhadap missing value dan anomali.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = "../data/teen_mental_health.csv"

df = pd.read_csv(data)
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,mental_health_risk_score,sleep_quality,digital_wellbeing_flag
0,14,male,7.9,Facebook,7.4,2.9,3.01,1.5,low,2,2,1,0,5,Fair,At Risk
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,19,Good,Moderate
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,8,Fair,Healthy
3,15,male,7.4,YouTube,6.9,1.6,3.48,0.8,medium,1,7,9,0,17,Fair,Moderate
4,15,female,4.7,All Platforms,4.9,3.0,2.37,1.4,medium,3,5,2,0,10,Poor,Moderate

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  mental_health_risk_score  1200 non-null   int64
 14  sleep_quality             1200 non-null   object
 15  digital_wellbeing_flag    1200 non-null   object
dtypes: float64(5), int64(6), object(5)
memory usage: 150.1+ KB

Dari informasi di atas, dapat diketahui jumlah baris dan kolom dalam dataset, tipe data masing-masing variabel, serta indikasi awal adanya missing value.

In [4]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,mental_health_risk_score
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833,16.647500
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704,5.038128
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000,3.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000,13.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000,17.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000,20.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000,30.000000

Statistik deskriptif digunakan untuk melihat ringkasan data numerik seperti nilai rata-rata, minimum, maksimum, dan standar deviasi.

In [5]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
mental_health_risk_score    0
sleep_quality               0
digital_wellbeing_flag      0
dtype: int64

Pengecekan missing value dilakukan untuk mengetahui apakah terdapat data yang tidak lengkap pada setiap atribut.

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label',
       'mental_health_risk_score', 'sleep_quality', 'digital_wellbeing_flag'],
      dtype='object')

## Kesimpulan Awal

Berdasarkan hasil eksplorasi awal, dataset memiliki sejumlah atribut yang mencakup demografi remaja, perilaku penggunaan media sosial dan gaya hidup (seperti durasi screen time dan jam tidur), serta indikator kesehatan mental (seperti tingkat stres, kecemasan, dan kesejahteraan digital).

Beberapa variabel masih perlu diproses lebih lanjut, seperti penanganan missing value (jika ada), transformasi tipe data, serta pembuatan fitur baru agar dapat digunakan secara optimal pada tahap analisis dan pemodelan berikutnya.